export const UZ = {
  // Navigation
  nav: {
    dashboard: "Asosiy",
    meals: "Ovqatlarim",
    stats: "Statistika",
    profile: "Profil",
    subscription: "Obunalar",
  },

  // Dashboard
  dashboard: {
    title: "Bugungi kaloriya",
    remaining: "Qolgan",
    consumed: "Iste'mol qilingan",
    macros: "Makro moddalar",
    protein: "Oqsil",
    carbs: "Uglevod",
    fat: "Yog'",
    addMeal: "Ovqat qo'shish",
    uploadImage: "Yuklash",
    noMeals: "Bugun ovqat qo'shilmagan",
  },

  // Onboarding
  onboarding: {
    welcome: "Xush kelibsiz!",
    step1: "Ism familiya",
    step2: "Telefon raqam",
    step3: "Yosh",
    step4: "Vazn (kg)",
    step5: "Bo'y (sm)",
    step6: "Haftada necha marta zalga borasiz?",
    step7: "Maqsad",
    goal_lose: "Ozish",
    goal_maintain: "Vazn saqlash",
    goal_gain: "Vazn olish",
    next: "Keyingi",
    back: "Orqaga",
    finish: "Tugatish",
    firstName: "Ismingiz",
    lastName: "Familiyangiz",
    phone: "Telefon",
    age: "Yoshingiz",
    weight: "Vazningiz (kg)",
    height: "Bo'yingiz (sm)",
    workoutFrequency: "Haftada necha marta zalga borasiz?",
    goal: "Maqsad",
    times_per_week: "marta/hafta",
  },

  // Meals
  meals: {
    title: "Ovqatlar",
    addMeal: "Ovqat qo'shish",
    uploadImage: "Yuklash",
    mealName: "Ovqat nomi",
    calories: "Kaloriya",
    protein: "Oqsil",
    carbs: "Uglevod",
    fat: "Yog'",
    delete: "O'chirish",
    edit: "Tahrirlash",
    save: "Saqlash",
    cancel: "Bekor qilish",
    notFood: "Bu rasm ovqatga o'xshamaydi.",
    disclaimer: "Qiymatlar taxminiy hisoblanadi.",
    notFoundFood: "Sizda bugun ovqat qo'shilmagan.",
  },

  // Stats
  stats: {
    title: "Statistika",
    today: "Bugun",
    week: "Hafta",
    month: "Oy",
    calendar: "Kalendar",
    totalCalories: "Jami kaloriya",
    avgCalories: "O'rtacha kaloriya",
    weight: "Vazn",
    weightProgress: "Vazn o'zgarishi",
    selectDate: "Sanani tanlang",
    noData: "Ma'lumot yo'q",
  },

  // Profile
  profile: {
    title: "Profil",
    personalInfo: "Shaxsiy ma'lumotlar",
    calorieTarget: "Kaloriya maqsadi",
    bmr: "BMR",
    tdee: "TDEE",
    dailyCalories: "Kunlik kaloriya",
    macroTarget: "Makro moddalar maqsadi",
    editProfile: "Profilni tahrirlash",
    updateWeight: "Vazni yangilash",
    logout: "Chiqish",
    firstName: "Ism",
    lastName: "Familiya",
    phone: "Telefon",
    age: "Yosh",
    weight: "Vazn",
    height: "Bo'y",
    goal: "Maqsad",
  },

  // Common
  common: {
    loading: "Yuklanmoqda...",
    error: "Xato yuz berdi",
    success: "Muvaffaqiyatli",
    save: "Saqlash",
    cancel: "Bekor qilish",
    delete: "O'chirish",
    edit: "Tahrirlash",
    close: "Yopish",
    back: "Orqaga",
    next: "Keyingi",
    finish: "Tugatish",
    ok: "OK",
    yes: "Ha",
    no: "Yo'q",
    time: "Vaqt",
  },

  // Errors
  errors: {
    required: "Majburiy maydon",
    invalidPhone: "Noto'g'ri telefon raqami",
    invalidAge: "Noto'g'ri yosh",
    invalidWeight: "Noto'g'ri vazn",
    invalidHeight: "Noto'g'ri bo'y",
    networkError: "Tarmoq xatosi",
    serverError: "Server xatosi",
    userNotFound: "Foydalanuvchi topilmadi",
    invalidCredentials: "Telefon raqami yoki parol noto'g'ri",
    userExists: "Bu telefon raqami bilan foydalanuvchi allaqachon mavjud",
    uploadFailed: "Yuklash muvaffaqiyatsiz bo'ldi",
    deleteFailed: "O'chirish muvaffaqiyatsiz bo'ldi",
    noImage: "Rasm tanlang",
    invalidImage: "Bu rasm ovqatga o'xshamaydi",
    mealNotFound: "Ovqat topilmadi",
    updateFailed: "Yangilash muvaffaqiyatsiz bo'ldi",
    loadingFailed: "Ma'lumot yuklanishida xato",
    authFailed: "Autentifikatsiya muvaffaqiyatsiz bo'ldi",
    tokenExpired: "Sessiya muddati tugadi",
    unauthorized: "Ruxsat berilmagan",
    forbidden: "Kirishga ruxsat yo'q",
    badRequest: "Noto'g'ri so'rov",
    tooManyRequests: "Juda ko'p so'rovlar. Biroz kuting.",
  },

  // Success Messages
  success: {
    registered: "Muvaffaqiyatli ro'yxatdan o'tdingiz",
    loggedIn: "Muvaffaqiyatli kiridingiz",
    loggedOut: "Muvaffaqiyatli chiqdingiz",
    mealAdded: "Ovqat muvaffaqiyatli qo'shildi",
    mealDeleted: "Ovqat muvaffaqiyatli o'chirildi",
    weightUpdated: "Vazn muvaffaqiyatli yangilandi",
    profileUpdated: "Profil muvaffaqiyatli yangilandi",
    saved: "Muvaffaqiyatli saqlandi",
  },
};
